// 365 Calming Music Suggestions for Anjeer Desk
// Instrumental pieces suitable for reading, studying, and quiet reflection

module.exports = [
  { day: 1, title: "Weightless", artist: "Marconi Union", url: "" },
  { day: 2, title: "Clair de Lune", artist: "Claude Debussy", url: "" },
  { day: 3, title: "Gymnopédie No. 1", artist: "Erik Satie", url: "" },
  { day: 4, title: "Air on the G String", artist: "Johann Sebastian Bach", url: "" },
  { day: 5, title: "Canon in D", artist: "Johann Pachelbel", url: "" },
  { day: 6, title: "The Four Seasons - Spring", artist: "Antonio Vivaldi", url: "" },
  { day: 7, title: "Moonlight Sonata", artist: "Ludwig van Beethoven", url: "" },
  { day: 8, title: "Nocturne in E-flat major", artist: "Frédéric Chopin", url: "" },
  { day: 9, title: "Ave Maria", artist: "Franz Schubert", url: "" },
  { day: 10, title: "Für Elise", artist: "Ludwig van Beethoven", url: "" },
  { day: 11, title: "The Swan", artist: "Camille Saint-Saëns", url: "" },
  { day: 12, title: "Adagio for Strings", artist: "Samuel Barber", url: "" },
  { day: 13, title: "Nimrod", artist: "Edward Elgar", url: "" },
  { day: 14, title: "Prelude in C Major", artist: "Johann Sebastian Bach", url: "" },
  { day: 15, title: "Liebestraum", artist: "Franz Liszt", url: "" },
  { day: 16, title: "Reverie", artist: "Claude Debussy", url: "" },
  { day: 17, title: "The Girl with the Flaxen Hair", artist: "Claude Debussy", url: "" },
  { day: 18, title: "Arabesque No. 1", artist: "Claude Debussy", url: "" },
  { day: 19, title: "Pavane pour une infante défunte", artist: "Maurice Ravel", url: "" },
  { day: 20, title: "Boléro", artist: "Maurice Ravel", url: "" },
  { day: 21, title: "Gymnopédie No. 2", artist: "Erik Satie", url: "" },
  { day: 22, title: "Gymnopédie No. 3", artist: "Erik Satie", url: "" },
  { day: 23, title: "Gnossienne No. 1", artist: "Erik Satie", url: "" },
  { day: 24, title: "Gnossienne No. 2", artist: "Erik Satie", url: "" },
  { day: 25, title: "Gnossienne No. 3", artist: "Erik Satie", url: "" },
  { day: 26, title: "Cello Suite No. 1", artist: "Johann Sebastian Bach", url: "" },
  { day: 27, title: "Cello Suite No. 2", artist: "Johann Sebastian Bach", url: "" },
  { day: 28, title: "Brandenburg Concerto No. 3", artist: "Johann Sebastian Bach", url: "" },
  { day: 29, title: "Water Music", artist: "George Frideric Handel", url: "" },
  { day: 30, title: "The Four Seasons - Summer", artist: "Antonio Vivaldi", url: "" },
  { day: 31, title: "The Four Seasons - Autumn", artist: "Antonio Vivaldi", url: "" },
  { day: 32, title: "The Four Seasons - Winter", artist: "Antonio Vivaldi", url: "" },
  { day: 33, title: "Symphony No. 6 'Pastoral'", artist: "Ludwig van Beethoven", url: "" },
  { day: 34, title: "Piano Sonata No. 14", artist: "Ludwig van Beethoven", url: "" },
  { day: 35, title: "Nocturne in C-sharp minor", artist: "Frédéric Chopin", url: "" },
  { day: 36, title: "Waltz in D-flat major", artist: "Frédéric Chopin", url: "" },
  { day: 37, title: "Prelude in E minor", artist: "Frédéric Chopin", url: "" },
  { day: 38, title: "Ballade No. 1", artist: "Frédéric Chopin", url: "" },
  { day: 39, title: "Impromptu in G-flat major", artist: "Frédéric Chopin", url: "" },
  { day: 40, title: "The Lark Ascending", artist: "Ralph Vaughan Williams", url: "" },
  { day: 41, title: "Fantasia on a Theme", artist: "Ralph Vaughan Williams", url: "" },
  { day: 42, title: "The Planets - Venus", artist: "Gustav Holst", url: "" },
  { day: 43, title: "The Planets - Neptune", artist: "Gustav Holst", url: "" },
  { day: 44, title: "Peer Gynt Suite - Morning Mood", artist: "Edvard Grieg", url: "" },
  { day: 45, title: "Peer Gynt Suite - Anitra's Dance", artist: "Edvard Grieg", url: "" },
  { day: 46, title: "Swan Lake - Scene", artist: "Pyotr Ilyich Tchaikovsky", url: "" },
  { day: 47, title: "The Nutcracker - Waltz of the Flowers", artist: "Pyotr Ilyich Tchaikovsky", url: "" },
  { day: 48, title: "Serenade for Strings", artist: "Pyotr Ilyich Tchaikovsky", url: "" },
  { day: 49, title: "Pictures at an Exhibition", artist: "Modest Mussorgsky", url: "" },
  { day: 50, title: "The Moldau", artist: "Bedřich Smetana", url: "" },
  // Continuing with more diverse music - I'll need to add all 365 entries
  // For now, this is a template showing the structure
];
